export const Hero = () => (
    <section class="hero is-medium is-primary is-bold">
        <div class="hero-body">
            <div class="container is-centered">
                <h1 class="title">
                    AI Art Store
                </h1>
                <h2 class="subtitle">
                    Artwork generated by Artificial Inteligence
                </h2>
                <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Iure, at.</p>
            </div>
        </div>
    </section>
)